//satVocabulary, the demo site only has around 200 words
satVocabulary = [
{	"word":	 "abbess",	"explanation":  	"A lady who is the head of a nunnery",	"category":	"noun"	},
{	"word":	 "abbot",	"explanation":  	"A man who is the head of a community of monks",	"category":	"noun"	},
{	"word":	 "abed",	"explanation":  	"on a bed",	"category":	"adverb"	},
{	"word":	 "abet",	"explanation":  	"To aid, promote, or encourage the commission of (an offense)", 	"category":	"verb"	},
{	"word":	 "abhorrence",	"explanation":  	"The act of detesting extremely",	"category":	"noun"	},
{	"word":	 "awaken",	"explanation":  	"To rouse from sleep; to arouse, as emotion, interest, or the like",	"category":	"verb"	},
{	"word":	 "awry", 	"explanation":  	"Out of the proper form, direction, or position", 	"category":	"adverb"	},
{	"word":	 "aye",	"explanation":  	"An expression of assent,especially in voting",	"category":	"noun"	},
{	"word":	 "azalea",	"explanation":  	"A deciduous flowering shrub",	"category":	"noun"	},
{	"word":	 "azure", 	"explanation":  	"The color of the sky",	"category":	"noun"	},
{	"word":	 "Baconian", 	"explanation":  	"Of or pertaining to Lord Bacon or his inductive system of philosophy",	"category":	"adjective"	},
{	"word":	 "bacterium", 	"explanation":  	"A microbe",	"category":	"noun"	},
{	"word":	 "badger", 	"explanation":  	"To pester",	"category":	"verb"	},
{	"word":	 "baffle", 	"explanation":  	"To foil or bewilder", 	"category":	"verb"	},
{	"word":	 "bailiff",	"explanation":  	"An officer of court having custody of prisoners under arraignment", 	"category":	"noun"	},
{	"word":	 "bursar", 	"explanation":  	"A treasurer (of a college or university)", 	"category":	"noun"	},
{	"word":	 "bustle", 	"explanation":  	"To hurry", 	"category":	"verb"	},
{	"word":	 "butt", 	"explanation":  	"To strike with or as with the head, or horns", 	"category":	"verb"	},
{	"word":	 "butte", 	"explanation":  	"A conspicuous hill with steep sides and a flat top, generally isolated", 	"category":	"noun"	},
{	"word":	 "buttress",	"explanation":  	"A support or prop", 	"category":	"noun"	},
{	"word":	 "cabal", 	"explanation":  	"A number of persons secretly united for political purpose", 	"category":	"noun"	},
{	"word":	 "cabalism", 	"explanation":  	"Superstitious devotion to one's religion",	"category":	"noun"	},
{	"word":	 "cabinet",	"explanation":  	"A body of advisers to the president,  ministry", 	"category":	"noun"	},
{	"word":	 "cacophony", 	"explanation":  	"A  harsh, or discordant sound or combination of sounds or tones",	"category":	"noun"	},
{	"word":	 "cadaverous",	"explanation":  	"Resembling a corpse",	"category":	"adjective"	},
{	"word":	 "cycloid", 	"explanation":  	"Like a circle", 	"category":	"adjective"	},
{	"word":	 "cygnet", 	"explanation":  	"A young swan", 	"category":	"noun"	},
{	"word":	 "cynical", 	"explanation":  	"Exhibiting moral skepticism", 	"category":	"adjective"	},
{	"word":	 "cynicism", 	"explanation":  	"Contempt for the opinions of others and of what others value", 	"category":	"noun"	},
{	"word":	 "cynosure", 	"explanation":  	"A person or thing  to which general interest or attention is directed", 	"category":	"noun"	},
{	"word":	 "daring", 	"explanation":  	"Brave", 	"category":	"adjective"	},
{	"word":	 "darkling",  	"explanation":  	"relating to growing darkness",	"category":	"adjective"	},
{	"word":	 "Darwinism", 	"explanation":  	"The doctrine that natural selection has been the prime cause of evolution of species", 	"category":	"noun"	},
{	"word":	 "dastard", 	"explanation":  	"A base coward", 	"category":	"noun"	},
{	"word":	 "datum",	"explanation":  	"A premise, starting-point, or given fact",	"category":	"noun"	},
{	"word":	 "duteous", 	"explanation":  	"Showing submission to natural superiors", 	"category":	"adjective"	},
{	"word":	 "dutiable",  	"explanation":  	"Subject to a duty, especially a customs duty", 	"category":	"adjective"	},
{	"word":	 "dutiful", 	"explanation":  	"Obedient", 	"category":	"adjective"	},
{	"word":	 "dwindle",	"explanation":  	"To diminish or become less", 	"category":	"verb"	},
{	"word":	 "dyne", 	"explanation":  	"The force applied to a mass of one gram for 1 second, a velocity of 1 cm/s",   	"category":	"noun"	},
{	"word":	 "earnest", 	"explanation":  	"showing sincere and intense conviction", 	"category":	"adjective"	},
{	"word":	 "earthenware", 	"explanation":  	"Anything made of clay and baked in a kiln or dried in the sun", 	"category":	"noun"	},
{	"word":	 "eatable", 	"explanation":  	"Edible",	"category":	"adjective"	},
{	"word":	 "ebullient", 	"explanation":  	"Showing enthusiasm or exhilaration of feeling",	"category":	"adjective"	},
{	"word":	 "eccentric",	"explanation":  	"Peculiar",	"category":	"adjective"	},
{	"word":	 "extremity", 	"explanation":  	"The utmost point, side, or border of something",	"category":	"noun"	},
{	"word":	 "extricate", 	"explanation":  	"Disentangle", 	"category":	"verb"	},
{	"word":	 "extrude",	"explanation":  	"To drive out or away",	"category":	"verb"	},
{	"word":	 "exuberance",  	"explanation":  	"Rich supply", 	"category":	"noun"	},
{	"word":	 "exuberant",  	"explanation":  	"Filled with a lively energy and excitement", 	"category":	"adjective"	},
{	"word":	 "fabricate", 	"explanation":  	"To invent fancifully or falsely", 	"category":	"verb"	},
{	"word":	 "fabulous", 	"explanation":  	"Incredible, extraordinary", 	"category":	"adjective"	},
{	"word":	 "facet", 	"explanation":  	"One of the small triangular plane surfaces of a diamond or other gem", 	"category":	"noun"	},
{	"word":	 "facetious", 	"explanation":  	"Treating serious issues with inappropriate humor",	"category":	"adjective"	},
{	"word":	 "facial",	"explanation":  	"Pertaining to the face",	"category":	"adjective"	},
{	"word":	 "facile", 	"explanation":  	"appearing simple by ignoring the true complexities of an issue", 	"category":	"adjective"	},
{	"word":	 "facilitate", 	"explanation":  	"To make easier to do", 	"category":	"verb"	},
{	"word":	 "facility", 	"explanation":  	"Space or equipment necessary for some activities",	"category":	"noun"	},
{	"word":	 "facsimile", 	"explanation":  	"Make a copy of", 	"category":	"verb"	},
{	"word":	 "faction", 	"explanation":  	"A samll organized political group with a larg one", 	"category":	"noun"	},
{	"word":	 "gauge", 	"explanation":  	"An instrument for measuring the magnitude or amount", 	"category":	"noun"	},
{	"word":	 "gaiety", 	"explanation":  	"the state of being joyful", 	"category":	"noun"	},
{	"word":	 "gaily", 	"explanation":  	"In a cherrful way", 	"category":	"adverb"	},
{	"word":	 "gait", 	"explanation":  	"manner of walking", 	"category":	"noun"	},
{	"word":	 "gallant", 	"explanation":  	"Possessing a brave or chivalrous spirit",	"category":	"adjective"	},
{	"word":	 "galore",	"explanation":  	"Abundant",	"category":	"adjective"	},
{	"word":	 "galvanic",	"explanation":  	"Relating to electricity produced by chemical action; sudden and dramatic", 	"category":	"adjective"	},
{	"word":	 "galvanism",	"explanation":  	"Current electricity, especially that arising from chemical action",	"category":	"noun"	},
{	"word":	 "galvanize",	"explanation":  	"To shock or excite (someone)",	"category":	"verb"	},
{	"word":	 "gamble",	"explanation":  	"To risk money or other possession on an event , chance, or contingency",  	"category":	"verb"	},
{	"word":	 "habitable",  	"explanation":  	"Fit to be dwelt in", 	"category":	"adjective"	},
{	"word":	 "habitant", 	"explanation":  	"Dweller", 	"category":	"noun"	},
{	"word":	 "habitual", 	"explanation":  	"According to usual practice", 	"category":	"adjective"	},
{	"word":	 "habitude", 	"explanation":  	"native or essential character", 	"category":	"noun"	},
{	"word":	 "hackney", 	"explanation":  	"A horse or pony used in harness",	"category":	"noun"	},
{	"word":	 "haggard", 	"explanation":  	"Worn and gaunt in appearance", 	"category":	"adjective"	},
{	"word":	 "halcyon",	"explanation":  	"Calm and happy", 	"category":	"adjective"	},
{	"word":	 "hale", 	"explanation":  	"Of sound and vigorous health", 	"category":	"adjective"	},
{	"word":	 "handwriting",	"explanation":  	"Writing done by hand", 	"category":	"noun"	},
{	"word":	 "hanger-on", 	"explanation":  	"A person that hangs around another person or a group in a sycophantic manner", 	"category":	"noun"	},
{	"word":	 "ichthyic", 	"explanation":  	"Fishlike", 	"category":	"adjective"	},
{	"word":	 "ichthyology", 	"explanation":  	"The branch of zoology that treats of fishes", 	"category":	"noun"	},
{	"word":	 "ichthyosaur", 	"explanation":  	"A fossil reptile", 	"category":	"noun"	},
{	"word":	 "icily", 	"explanation":  	"Frigidly", 	"category":	"adverb"	},
{	"word":	 "iciness", 	"explanation":  	"The state of being icy", 	"category":	"noun"	},
{	"word":	 "isolate", 	"explanation":  	"To separate from others of its kind", 	"category":	"verb"	},
{	"word":	 "isothermal", 	"explanation":  	"Having or marking equality of temperature",	"category":	"adjective"	},
{	"word":	 "itinerant",	"explanation":  	"Wandering", 	"category":	"adjective"	},
{	"word":	 "itinerary", 	"explanation":  	"A detailed account or diary of a journey",	"category":	"noun"	},
{	"word":	 "itinerate", 	"explanation":  	"To travel from place to place to perform one's professional duty",	"category":	"verb"	},
{	"word":	 "jargon", 	"explanation":  	"highly technical words or speech that are difficult for others to understand", 	"category":	"noun"	},
{	"word":	 "jaundice", 	"explanation":  	"A medical condition characterized by yellowing of the skin and the whites of the eyes ",	"category":	"noun"	},
{	"word":	 "jeopardize", 	"explanation":  	"To put at risk of being harmed",	"category":	"verb"	},
{	"word":	 "jingo", 	"explanation":  	"a strong supporter of policy in favor of war in the name of patriotism", 	"category":	"noun"	},
{	"word":	 "jocose",	"explanation":  	"Done or made in a joke", 	"category":	"adjective"	},
{	"word":	 "juror", 	"explanation":  	"One who serves on a jury ", 	"category":	"noun"	},
{	"word":	 "joust",	"explanation":  	"To engage in a medieval sports contest with lances on horseback", 	"category":	"verb"	},
{	"word":	 "justification", 	"explanation":  	"The action of showing something to be right", 	"category":	"noun"	},
{	"word":	 "juvenile", 	"explanation":  	"Characteristic of youth",	"category":	"adjective"	},
{	"word":	 "juxtapose",  	"explanation":  	"To place close together for contrasting effect", 	"category":	"verb"	},
{	"word":	 "keepsake", 	"explanation":  	"Anything kept or given to be kept for the sake of the giver", 	"category":	"noun"	},
{	"word":	 "kerchief", 	"explanation":  	"A square of linen, silk, or other material, used as a covering for the head or neck", 	"category":	"noun"	},
{	"word":	 "kernel", 	"explanation":  	"A grain or seed", 	"category":	"noun"	},
{	"word":	 "kiln", 	"explanation":  	"An oven or furnace for baking, burning, or drying industrial products", 	"category":	"noun"	},
{	"word":	 "kiloliter", 	"explanation":  	"One thousand liters", 	"category":	"noun"	},
{	"word":	 "knavery",	"explanation":  	"Deceitfulness, dishonesty", 	"category":	"noun"	},
{	"word":	 "knead", 	"explanation":  	"To mix and work into a homogeneous mass, especially with the hands", 	"category":	"noun"	},
{	"word":	 "knickknack",	"explanation":  	"A small worthless object, more for ornament than use",	"category":	"noun"	},
{	"word":	 "knight",	"explanation":  	"A man in the Middle Ages who served his sovereign as a  soldier in armor ",	"category":	"noun"	},
{	"word":	 "knighthood",	"explanation":  	"The title or rank of a knight", 	"category":	"noun"	},
{	"word":	 "laborious", 	"explanation":  	"involving hard or tedious work", 	"category":	"adjective"	},
{	"word":	 "labyrinth", 	"explanation":  	"A maze", 	"category":	"noun"	},
{	"word":	 "lacerate",	"explanation":  	"To tear rudely or raggedly", 	"category":	"verb"	},
{	"word":	 "lackadaisical", 	"explanation":  	"Listless,carelessly lazy", 	"category":	"adjective"	},
{	"word":	 "lactation", 	"explanation":  	"The secretion of milk",	"category":	"noun"	},
{	"word":	 "luxuriant", 	"explanation":  	"Abundant or superabundant in growth", 	"category":	"adjective"	},
{	"word":	 "luxuriate", 	"explanation":  	"To live  in a luxurious way", 	"category":	"verb"	},
{	"word":	 "lying", 	"explanation":  	"not telling the truth", 	"category":	"adjective"	},
{	"word":	 "lyre", 	"explanation":  	"One of the most ancient  stringed instruments of the harp class", 	"category":	"noun"	},
{	"word":	 "lyric", 	"explanation":  	"Fitted for expression in song", 	"category":	"adjective"	},
{	"word":	 "macadamize", 	"explanation":  	"To cover or pave, as a path or roadway, with small broken stone",	"category":	"verb"	},
{	"word":	 "machinery", 	"explanation":  	"The parts of a machine or engine, taken collectively", 	"category":	"noun"	},
{	"word":	 "machinist", 	"explanation":  	"One who makes or repairs machines, or uses metal-working tools", 	"category":	"noun"	},
{	"word":	 "macrocosm",	"explanation":  	"The whole of any sphere or a complex structure , contrasted with a small part of it",	"category":	"noun"	},
{	"word":	 "madden",	"explanation":  	"To make(someone) extremely irritated",	"category":	"verb"	},
{	"word":	 "myriad", 	"explanation":  	"A vast indefinite number", 	"category":	"noun"	},
{	"word":	 "mystic", 	"explanation":  	"One who professes divine illumination, or relies upon meditation to acquire truth", 	"category":	"noun"	},
{	"word":	 "mystification", 	"explanation":  	"The act of artfully perplexing", 	"category":	"noun"	},
{	"word":	 "myth",  	"explanation":  	"A fictitious narrative presented as historical, but without any basis of fact", 	"category":	"noun"	},
{	"word":	 "mythology", 	"explanation":  	"A collection of legends cherished by a race concerning gods and heroes",	"category":	"noun"	},
{	"word":	 "nameless", 	"explanation":  	"Having no fame or reputation", 	"category":	"adjective"	},
{	"word":	 "naphtha", 	"explanation":  	"A colorless and flammable oil containing various hydrocarbons used as a solvent", 	"category":	"noun"	},
{	"word":	 "Narcissus", 	"explanation":  	"The son of Cephisus who fell in love with his reflection and became flower",	"category":	"noun"	},
{	"word":	 "narrate",  	"explanation":  	"To tell a story", 	"category":	"verb"	},
{	"word":	 "narration",	"explanation":  	"The act of recounting the particulars of an event in the order of time", 	"category":	"noun"	},
{	"word":	 "nunnery", 	"explanation":  	"A convent for nuns", 	"category":	"noun"	},
{	"word":	 "nuptial", 	"explanation":  	"Of or relating to marriage, especially to the marriage ceremony", 	"category":	"adjective"	},
{	"word":	 "nurture", 	"explanation":  	"The process of fostering or promoting growth", 	"category":	"noun"	},
{	"word":	 "nutriment", 	"explanation":  	"That which nourishes",	"category":	"noun"	},
{	"word":	 "nutritive",  	"explanation":  	"Having nutritious properties", 	"category":	"adjective"	},
{	"word":	 "oaken", 	"explanation":  	"Made of or from oak", 	"category":	"adjective"	},
{	"word":	 "oakum", 	"explanation":  	"Losse fiber obtained by untwisting old hemp rope", 	"category":	"noun"	},
{	"word":	 "obdurate", 	"explanation":  	"not willing to change one's opinion or the way of doing things", 	"category":	"adjective"	},
{	"word":	 "obelisk", 	"explanation":  	"A square shaft with pyramidal top, usually monumental or commemorative", 	"category":	"noun"	},
{	"word":	 "obese", 	"explanation":  	"overweight", 	"category":	"adjective"	},
{	"word":	 "overstride", 	"explanation":  	"To step beyond", 	"category":	"verb"	},
{	"word":	 "overthrow",	"explanation":  	"To vanquish an established ruler or government", 	"category":	"verb"	},
{	"word":	 "overtone", 	"explanation":  	"A music tone above a fundamental note; a subtle implication", 	"category":	"noun"	},
{	"word":	 "overture",  	"explanation":  	"An instrumental prelude to an opera, oratorio, or ballet", 	"category":	"noun"	},
{	"word":	 "overweight",	"explanation":  	"Preponderance in weight", 	"category":	"noun"	},
{	"word":	 "pacify", 	"explanation":  	"To bring into a peaceful state", 	"category":	"verb"	},
{	"word":	 "packet", 	"explanation":  	"A bundle, as of letters", 	"category":	"noun"	},
{	"word":	 "pact", 	"explanation":  	"A formal agreement", 	"category":	"noun"	},
{	"word":	 "pagan", 	"explanation":  	"A worshiper of false gods", 	"category":	"noun"	},
{	"word":	 "pageant",	"explanation":  	"An outdoor performance of a historical scene or  an elaborate colorful exhibition",	"category":	"noun"	},
{	"word":	 "putrescent",  	"explanation":  	"Undergoing decomposition of animal or vegetable",	"category":	"adjective"	},
{	"word":	 "pyre", 	"explanation":  	"A heap of combustibles arranged for burning a dead body", 	"category":	"noun"	},
{	"word":	 "pyromania", 	"explanation":  	"An insane propensity to set things on fire", 	"category":	"noun"	},
{	"word":	 "pyrotechnic",	"explanation":  	"Pertaining to fireworks", 	"category":	"adjective"	},
{	"word":	 "pyx",   	"explanation":  	"A vessel or casket in which the host is preserved", 	"category":	"noun"	},
{	"word":	 "quackery", 	"explanation":  	"the treatments used by unkillful doctors or by people who nprented to be doctors", 	"category":	"noun"	},
{	"word":	 "quadrate", 	"explanation":  	"To divide into quarters", 	"category":	"verb"	},
{	"word":	 "quadruple", 	"explanation":  	"To multiply by four", 	"category":	"verb"	},
{	"word":	 "qualification", 	"explanation":  	"A requisite for an employment, position, right, or privilege",	"category":	"noun"	},
{	"word":	 "qualify", 	"explanation":  	"To furnish with requisite ability, character, knowledge, skill, or possessions", 	"category":	"verb"	},
{	"word":	 "quietus",  	"explanation":  	"A silencing, suppressing, or ending", 	"category":	"noun"	},
{	"word":	 "quintessence", 	"explanation":  	"The essence of a thing in its purest and most concentrated  form", 	"category":	"noun"	},
{	"word":	 "quintet", 	"explanation":  	"Musical composition arranged for five voices or instruments", 	"category":	"noun"	},
{	"word":	 "quite", 	"explanation":  	"Fully, absolutely", 	"category":	"adverb"	},
{	"word":	 "quixotic", 	"explanation":  	"Chivalrous or romantic to a ridiculous or extravagant degree", 	"category":	"adjective"	},
{	"word":	 "rabid", 	"explanation":  	"Affected with rabies, a fatal disease caused by bitten by an infected dogs", 	"category":	"adjective"	},
{	"word":	 "racy", 	"explanation":  	"Exciting or exhilarating ", 	"category":	"adjective"	},
{	"word":	 "radiance", 	"explanation":  	"Brilliant or sparkling luster", 	"category":	"noun"	},
{	"word":	 "radiate", 	"explanation":  	"To extend in all directions, as from a source or focus", 	"category":	"verb"	},
{	"word":	 "radical", 	"explanation":  	"One who holds through views or advocates extreme measures",	"category":	"noun"	},
{	"word":	 "sacrifice", 	"explanation":  	"To make an offering of to deity, especially by presenting on an altar", 	"category":	"verb"	},
{	"word":	 "sacrificial", 	"explanation":  	"involving sacrifice", 	"category":	"adjective"	},
{	"word":	 "sacrilege",  	"explanation":  	"The act of violating or profaning anything sacred", 	"category":	"noun"	},
{	"word":	 "sacrilegious", 	"explanation":  	"lacking proper respect (as for God)", 	"category":	"adjective"	},
{	"word":	 "safeguard", 	"explanation":  	"To protect", 	"category":	"verb"	},
{	"word":	 "tableau", 	"explanation":  	"An arrangement of inanimate figures representing a scene from real life", 	"category":	"noun"	},
{	"word":	 "tacit", 	"explanation":  	"Understood or implied without being stated", 	"category":	"adjective"	},
{	"word":	 "taciturn", 	"explanation":  	"Disinclined to conversation, (of a person) reserved ", 	"category":	"adjective"	},
{	"word":	 "tack", 	"explanation":  	"A small sharp-pointed nail", 	"category":	"noun"	},
{	"word":	 "tact",  	"explanation":  	"adroitness and sensitivity in saying or doing things with difficult issues", 	"category":	"adjective"	},
{	"word":	 "ubiquitous", 	"explanation":  	"Being present everywhere", 	"category":	"adjective"	},
{	"word":	 "ulterior", 	"explanation":  	"Not so pertinent as the matter spoken of; intentionally hidden", 	"category":	"adjective"	},
{	"word":	 "ultimate",  	"explanation":  	"Being or happening at the end of a process", 	"category":	"adjective"	},
{	"word":	 "ultimatum", 	"explanation":  	"A final statement or proposal, as concerning terms or conditions", 	"category":	"noun"	},
{	"word":	 "ultramundane", 	"explanation":  	"Pertaining to supernatural things or to another life", 	"category":	"noun"	},
{	"word":	 "vacate", 	"explanation":  	"To leave", 	"category":	"verb"	},
{	"word":	 "vaccinate", 	"explanation":  	"To inoculate with vaccine virus or virus of cowpox", 	"category":	"verb"	},
{	"word":	 "vacillate", 	"explanation":  	"To waver, be indecisive", 	"category":	"verb"	},
{	"word":	 "vacuous", 	"explanation":  	"Empty, mindless.", 	"category":	"adjective"	},
{	"word":	 "vacuum", 	"explanation":  	"A space entirely devoid of matter",	"category":	"noun"	},
{	"word":	 "waif", 	"explanation":  	"A homeless, neglected wanderer", 	"category":	"noun"	},
{	"word":	 "waistcoat", 	"explanation":  	"A vest", 	"category":	"noun"	},
{	"word":	 "waive", 	"explanation":  	"To relinquish, especially temporarily, as a right or claim", 	"category":	"verb"	},
{	"word":	 "wampum", 	"explanation":  	"Beads strung on threads, formerly used among the American Indians as currency", 	"category":	"noun"	},
{	"word":	 "wane", 	"explanation":  	"To diminish in size and brilliancy", 	"category":	"noun"	},
{	"word":	 "yearling", 	"explanation":  	"An animal (a sheep, calf, or foal) past its first year and not yet two years old", 	"category":	"noun"	},
{	"word":	 "zealot", 	"explanation":  	"One who pursues an object in fanatical and  an immoderately partisan manner", 	"category":	"noun"	},
{	"word":	 "zeitgeist", 	"explanation":  	"The intellectual and moral tendencies that characterize any age or epoch", 	"category":	"noun"	},
{	"word":	 "zenith", 	"explanation":  	"The culminating-point of prosperity, influence, or greatness", 	"category":	"noun"	},
{	"word":	 "zephyr", 	"explanation":  	"Any soft, gentle wind", 	"category":	"noun"	},
{	"word":	 "zodiac", 	"explanation":  	"A belt encircling the heavens  within about 8° either side of the ecliptic ",	"category":	"noun"	}
];